### ISSUE TITLE
Password policy parameters

### ISSUE THREAD

**Issue by canonalis** [tiredofit/docker-openldap#1]
Password policy values will overwrite the default /etc/openldap/check_password.,conf values but fail to overwrite the /etc/openldap/ppm.conf.
![docker-compose_vars](https://user-images.githubusercontent.com/1898752/44680268-15ef8a80-a9f2-11e8-8aa4-70cacf9ef19d.JPG)
![check_password_var](https://user-images.githubusercontent.com/1898752/44680128-b1ccc680-a9f1-11e8-8974-db830b0470c9.JPG)
![ppm_minqualityvar](https://user-images.githubusercontent.com/1898752/44680141-b72a1100-a9f1-11e8-9fa2-f95541ed0863.JPG)
![ppm-minvars](https://user-images.githubusercontent.com/1898752/44680144-b98c6b00-a9f1-11e8-88a8-1794f14c2d07.JPG)

**Comment by tiredofit** [comment]
Thanks! Problem was in the `class-special` section of last screenshot. Some of the characters needed escaping. 
Resolved in 6.0.1 and being built on Dockerhub as we speak.
