### ISSUE TITLE
ulimit 1024 iset in start script

### ISSUE THREAD

**Issue by Anganthier** [tiredofit/docker-openldap#12]
Hi, 

I am running into a connection limit. I tried to set ulimit(nofile - soft and hard) in my docker-compose file, but ulimit of the slapd process is still set to 1024.

I found that you have hardcoded the ulimit -n call in the /etc/s6/services/10-openldap/run file. Could you please either remove that line or make that parameter configurable.

In my case it would be enough to set a global ulimit nofile in my docker config. I don't need a specific config value for the slapd process itself.

Thanks,
David Ecker

**Comment by tiredofit** [comment]
Sure thing I can make it configurable. I found that if set to a high value it chews up much more memory than it actually needs to and was recommended by OpenLDAP themselves. I'll turn it into a configurable variable which should give you what you need. I'm just in the middle of reworking all my base images and OpenLDAP hasn't been tested yet, I hope to have the testing completed by end of day and then will move them from my private repo to github.

**Comment by Anganthier** [comment]
You are right, you should limit the number of open files for slapd. The default of about 1 Million consumes several hundred of MB. 

In my case I have 1500 Clients connecting to slapd. So 1024 is too low for this environment. I increased the value to 20000 by setting the default for all processes on the container level.

I'll be able to test your new image on Jan, 3rd, 2020,

**Comment by tiredofit** [comment]
Great! Let me know. I've pushed to github and Docker Hub is just in a very long queue (2 days?) to get the new one built based on the other base image changes. Should be ready to go when you return.

**Comment by Anganthier** [comment]
It works, thanks.
