### ISSUE TITLE
ENABLE_NGINX=false breaks the container

### ISSUE THREAD

**Issue by jrevillard** [tiredofit/docker-openldap#13]
Hi,

In this case, in `/etc/cont-init.d/09-nginx`, the `liftoff` function is not called and the `/etc/cont-init.d/99-container` stop everything as the state file is not created.

Best,
Jerome

**Comment by tiredofit** [comment]
Thanks, Docker hub is on a loop right now building images and everythings gotten well out of sync.. I will review and build this manually and push manually shortly.

**Comment by tiredofit** [comment]
Problem fixed in `6.6.2` - Thanks for catching this.

**Comment by jrevillard** [comment]
It works thx!
