### ISSUE TITLE
BASE_DN is ignored

### ISSUE THREAD

**Issue by dmbasso** [tiredofit/docker-openldap#16]
Commit 9000a6c8 (2019-12-30) introduced a problem during container initialization, starting from line 53 of `/etc/cont-init.d/10-openldap`:

```
  IFS='.' read -a domain_elems <<< "${DOMAIN}"
  SUFFIX=""
  ROOT=""

  for elem in "${domain_elems[@]}" ; do
      if [ "x${SUFFIX}" = x ] ; then
          SUFFIX="dc=${elem}"
          ROOT="${elem}"
      else
          BASE_DN="${SUFFIX},dc=${elem}"
      fi
  done
```

This snippet overwrites the `BASE_DN` environment variable, and that loop does not build it correctly from `DOMAIN` for a domain bigger than two components (e.g. my.example.org will end in `BASE_DN=dc=my,dc=org`).

Bug aside, this image is very handy, thank you for your work.

**Comment by tiredofit** [comment]
Thanks!

Sometime about a year ago there was a PR to fix this before, and I'm certain I messed this up when updating the images a few months back to align with my other base images. I'll put this on the list to walk through the commits and find out where I've gone wrong.
