### ISSUE TITLE
Certificates should not be unconditionally chown'ed

### ISSUE THREAD

**Issue by frebib** [tiredofit/docker-openldap#17]
```
[cont-init.d] 10-openldap: executing...
chown: changing ownership of '/assets/slapd/certs/<name>': Read-only file system
chown: changing ownership of '/assets/slapd/certs/<name>': Read-only file system
.. etc
chown: changing ownership of '/assets/slapd/certs': Read-only file system
[cont-init.d] 10-openldap: exited 1.
[cont-init.d] 99-container: executing...
**********************************************************************************************************************
**********************************************************************************************************************
****                                                                                                              ****
****       ERROR - Some initialization scripts haven't completed - All services are now halted                    ****
****             - The following scripts in '/etc/cont-init.d' did not pass their completion check                ****
****                                                                                                              ****
**********************************************************************************************************************
**********************************************************************************************************************

10-openldap
```

These certificates are shared amongst a few containers on this host, and they do not need to be modified. They are mounted read-only inside the container and this causes the startup to fail

Offending chown:
https://github.com/tiredofit/docker-openldap/blob/4b51edb1514197b4d9f9a6a691957a4a1bc8deae/install/etc/cont-init.d/10-openldap#L164

**Comment by tiredofit** [comment]
Thanks, makes sense, I'm going to send a test build up to Docker Hub for you to test. Try pulling `tiredofit/openldap:develop`. If it works, I'll commit and then perform a `latest` build and also update `openldap-fusiondirectory`.

**Comment by frebib** [comment]
Yeah that looks good, thank you.
It would also be good to have a flag to disable those three `chown` calls all together. Nothing should be randomly changing file permissions on these systems anyway

**Comment by frebib** [comment]
Another, and IMO more effective solution around this would be allowing the user to override the `TLS_*_PATH` variables, so they could then mount them outside of the `/assets/slapd` directory. That would also give extra flexibility and would certainly help me out

**Comment by tiredofit** [comment]
Agreed - Adding a variabl to define the path more suitable. There is a catch though , you will need to dump your data to an ldif and manually change the path if you are working on an existing install. The TLS functionality is pretty finnicky in this image. I'll add this in today sometime for you.

**Comment by tiredofit** [comment]
New build `tiredofit/openldap:6.8.0` building on Docker Hub

New environment variables:
`TLS_CA_CRT_PATH` (Default: `/assets/slapd/certs`)
`TLS_CRT_PATH` (Default: `/assets/slapd/certs`)
`TLS_KEY_PATH` (Default: `/assets/slapd/certs`)
`TLS_DH_PARAM_PATH` (Default: `/assets/slapd/certs`)
`TLS_DH_PARAM_FILENAME` (Default `dhparam.pem`)
`TLS_DH_PARAM_KEYSIZE` (Default `2048`)
`TLS_RESET_PERMISSIONS` (Default `TRUE`)

This should give you what you need! Let me know if good and we can close this off.

**Comment by frebib** [comment]
Looks like the new build is doing what I need, thanks!

**Comment by moqmar** [comment]
Seems like it's only fixed on the first run though?

**Comment by moqmar** [comment]
Line 333 in /etc/cont-init.d/10-openldap seems to be the culprit, and line 464 might also be an issue.
