### ISSUE TITLE
chmod for custom scripts fails on read-only file systems

### ISSUE THREAD

**Issue by goldsam** [tiredofit/docker-openldap#31]
I was attempting to use your wonderful image in my k8s deployment by mounting my custom startup script directly under `/assets/custom-scripts/` from a [`configMap`](https://kubernetes.io/docs/concepts/configuration/configmap/) resource. I had been careful to ensure my file was [mounted as executable using `defaultMode`](https://github.com/kubernetes/kubernetes/issues/71356#issuecomment-441169334). Unfortunately, startup fails due the `chmod`  command which attempts to modify the file which in a read-only file system:

https://github.com/tiredofit/docker-openldap/blob/cc7c325a6fcff2907ae919d2e241145b3cbce237/install/assets/functions/10-openldap#L551-L559

I would argue that it should be the user's responsibility to ensure scripts are executable and not the startup script. The `chmod` command assumes the file system is writable, which forces a much more complex deployment approach.

**Comment by tiredofit** [comment]
I agree with this. I should not dictating this - It's up to to the user. Thanks for catching this - this has been around forever!

**Comment by tiredofit** [comment]
Tagged as `7.1.7`

**Comment by goldsam** [comment]
Awesome! Great project. Thanks for your hard work 😉
