### ISSUE TITLE
docker-compose combined  file

### ISSUE THREAD

**Issue by grharry** [tiredofit/docker-openldap#34]
After so many attempts to make it work I always come up with same results and nothing works. 
Even though this looks promising I suspect  its extremely complicated. 
From my personal experience I  always avoid s6 for multi-process containers.  

To conclude and get to end my frustration. 
I would appreciate it if you could share a simple and  working  docker-compose.yml  combined file for both services ldap and fusiond  with just the basic  modules for domain example.org or whatever! 

Kind regards, 
Harry.

**Comment by dginhoux** [comment]
I'm in the same way.... i just try with the example, create bind volumes with a poor "chmod 777 -R"... but nothing is working.

**Comment by grharry** [comment]
I guess if nobody feels like  answering this, you might as well close it! So we can forget all about it and try look for another solution elsewhere!

**Comment by eitch** [comment]
@grharry did you find another solution somewhere else?
