### ISSUE TITLE
[Feature Request][PR] Add contrib/autogroup overlay for dynamic group setups

### ISSUE THREAD

**Issue by jkrenzer** [tiredofit/docker-openldap#38]
Hi!

Thanks for the helpful image!

As dynlist ist not yet compatible with memberOf in openldap 2.4 (but judging from the docs might be in 2.5) autogroup is the only solution for using dynamic URL group expansion.

The overlay still compiles flawlessly, so I submitted a PR ( #37 ) if you like to add this functionality to your image.

Cheers,

Jörn

**Comment by tiredofit** [comment]
Thanks for this! Tagged as `tirdofit/openldap-7.1.13` however a a 7.1.14 is out right after to provide OpenLDAP 2.4.58 as well. :)
