### ISSUE TITLE
cp: cannot stat '/assets/slapd/config/bootstrap/scfhema/rfc2307bis/rfc2307bis.schema': No such file or directory

### ISSUE THREAD

**Issue by ilarrain** [tiredofit/docker-openldap#51]
Thanks for your work!
There is a typo in the line:
https://github.com/tiredofit/docker-openldap/blob/e65c56ca8ad164d763c8f57fe17a19a34bca1989/install/assets/functions/10-openldap#L708

scfhema should be schema.

**Comment by tiredofit** [comment]
Thanks for letting me know. I have updated the 2.6 branch with this fix to allow your rfc2307bis schemas to load.
